events {}

http {

server {

listen 80;

location / {

return 200 '<html>
<head>
<title>Microservices CI/CD</title>
<style>
body{
font-family: Arial;
background: linear-gradient(135deg,#667eea,#764ba2);
color:white;
text-align:center;
padding-top:100px;
}

.box{
background:rgba(255,255,255,0.1);
padding:40px;
width:400px;
margin:auto;
border-radius:15px;
box-shadow:0 10px 20px rgba(0,0,0,0.3);
}

a{
display:block;
margin-top:20px;
padding:10px;
background:white;
color:black;
text-decoration:none;
border-radius:8px;
font-weight:bold;
}

</style>
</head>

<body>

<div class="box">
<h1>Microservices CI/CD Project</h1>

<a href="/users">User Service</a>

<a href="/products">Product Service</a>

</div>

</body>
</html>';

add_header Content-Type text/html;

}

location /users {

proxy_pass http://user-service:5001/;

}

location /products {

proxy_pass http://product-service:5002/;

}

}

}